### ISSUE TITLE
usage: model_list and some common questions

### ISSUE THREAD

**Issue by chenchunhui97** [NetEase-Media/grps#3]
I want to konw:
1. support model list (a table includs hardware, backend, model name, dtype, optimization techs. )
2. does the project support service with concurrency? that is, if many client sent requests at the same time, will the deployment batch them and inference at once time?
3. can I put precessing & postprocessing in the deployment? instead of client.

**Comment by zhaocc1106** [comment]
> I want to konw:
> 
> 1. support model list (a table includs hardware, backend, model name, dtype, optimization techs. )
> 2. does the project support service with concurrency? that is, if many client sent requests at the same time, will the deployment batch them and inference at once time?
> 3. can I put precessing & postprocessing in the deployment? instead of client.

1. 框架是从支持推理后端角度来支持模型推理服务的，当前支持tensorflow、torch、tensorrt、tensorrt-llm、vllm等，模型支持列表就是基于每个框架开发的模型。硬件方面主要用于gpu硬件推理，对于tf、torch框架也可以选择跑在cpu，也都是推理后端决定的。具体推理后端见[推理后端](https://github.com/NetEase-Media/grps/blob/master/docs/7_InternalInferer.md)，以及单独的[grps_trtllm](https://github.com/NetEase-Media/grps_trtllm)、[grps_vllm](https://github.com/NetEase-Media/grps_vllm)工程。不同推理后端对应不同的镜像，见[镜像列表](https://github.com/NetEase-Media/grps/blob/master/docs/19_ImageList.md)。
2. 框架本身支持并发请求，也可以限制同一时间并发推理的个数，并且可以选择dynamic batching模式进行动态批处理请求，具体见[Batching](https://github.com/NetEase-Media/grps/blob/master/docs/13_Batching.md)。
3. 通过自定义工程即可进行服务端的自定义开发，进而进行前后处理。具体见：[自定义模型工程](https://github.com/NetEase-Media/grps/blob/master/docs/5_Customized.md)。

----
1. The framework supports model inference services from the perspective of supporting the inference backend. Currently, it supports frameworks such as TensorFlow, PyTorch, TensorRT, TensorRT-LLM, and VLLM. The model support list is based on models developed for each framework. On the hardware side, it is primarily used for GPU hardware inference, and for TensorFlow and PyTorch frameworks, it is also possible to choose to run on the CPU, which is determined by the inference backend. For specific inference backends, refer to [Inference Backend](https://github.com/NetEase-Media/grps/blob/master/docs/7_InternalInferer.md), as well as the individual [grps_trtllm](https://github.com/NetEase-Media/grps_trtllm) and [grps_vllm](https://github.com/NetEase-Media/grps_vllm) projects. Different inference backends correspond to different images, as listed in the [Image List](https://github.com/NetEase-Media/grps/blob/master/docs/19_ImageList.md).
2. The framework itself supports concurrent requests and can limit the number of concurrent inferences at the same time. It also offers the option to use dynamic batching mode for dynamic batch processing of requests. For details, refer to [Batching](https://github.com/NetEase-Media/grps/blob/master/docs/13_Batching.md).
3. Custom server-side development can be carried out through custom projects for further pre- and post-processing. For specifics, refer to [Custom Model Project](https://github.com/NetEase-Media/grps/blob/master/docs/5_Customized.md).
