### ISSUE TITLE
Start grps server(my_grps) failed

### ISSUE THREAD

**Issue by KkemChen** [NetEase-Media/grps#4]
![image](https://github.com/user-attachments/assets/dc5e5236-32a7-48f3-917f-b00a3c0d4c4d)

使用registry.cn-hangzhou.aliyuncs.com/opengrps/grps_gpu:grps1.1.0_cuda11.8_cudnn8.6_torch2.4.0_py3.10 镜像，`grpst torch_serve ./yolov8n.torchscript` 提示`Start grps server(my_grps) failed`

**Comment by zhaocc1106** [comment]
> registry.cn-hangzhou.aliyuncs.com/opengrps/grps_gpu:grps1.1.0_cuda11.8_cudnn8.6_torch2.4.0_py3.10

有些奇怪，没有错误日志，能否帮忙提供一下如下目录的一些文件？
ll ~/.grps/my_grps/

<img width="580" alt="image" src="https://github.com/user-attachments/assets/63d28af6-66d4-4caf-acaa-03eed6ef14e5">

**Comment by KkemChen** [comment]
![image](https://github.com/user-attachments/assets/3f120e90-4088-4a2c-b8ab-186c76321c85)

没有生成对应的文件

**Comment by zhaocc1106** [comment]
> ![image](https://private-user-images.githubusercontent.com/44298896/367133547-3f120e90-4088-4a2c-b8ab-186c76321c85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTY4MDQsIm5iZiI6MTcyNjE5NjUwNCwicGF0aCI6Ii80NDI5ODg5Ni8zNjcxMzM1NDctM2YxMjBlOTAtNDA4OC00YTJjLWI4YWItMTg2Yzc2MzIxYzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTViYzBhNThkOWYzMmI4OTU4ZDM0Mjc2YjhhZWU3MzlkOTRhYmIwMzZkYjZmMzdlMTA0M2M2Y2Q3MzQxZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LIG2Y03W3f9gz5zaSwA99Hp_4O19pjz7Kgp9DANaIY4)
> 
> 没有生成对应的文件

可否在该目录执行下脚本看看有什么错误？类似这样：
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/da99f856-fb38-407d-9f04-03dae087afa2">

**Comment by KkemChen** [comment]
![image](https://github.com/user-attachments/assets/fd9abac9-6bb8-491f-a374-98cb664d37e7)

**Comment by zhaocc1106** [comment]
> ![image](https://private-user-images.githubusercontent.com/44298896/367134723-fd9abac9-6bb8-491f-a374-98cb664d37e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTcxNzcsIm5iZiI6MTcyNjE5Njg3NywicGF0aCI6Ii80NDI5ODg5Ni8zNjcxMzQ3MjMtZmQ5YWJhYzktNmJiOC00OTFmLWEzNzQtOThjYjY2NGQzN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMjRiNDI4NzJhODg0NjE2NTdlZTBlYjA2OTM5NTMzMjgwYjQxYjJjYmQyNGY2ZDhjMjQ1OTNiYjhlYzg0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vwrgd9pCIIRzppbc66RnxsebKBEumE3wl4Pwgafm_Vc)

这个时候nohup.out有内容吗？谢谢

**Comment by KkemChen** [comment]
![image](https://github.com/user-attachments/assets/af217324-8b31-45d7-89c6-8c08501f369b)

**Comment by zhaocc1106** [comment]
> ![image](https://private-user-images.githubusercontent.com/44298896/367135422-af217324-8b31-45d7-89c6-8c08501f369b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTcyOTYsIm5iZiI6MTcyNjE5Njk5NiwicGF0aCI6Ii80NDI5ODg5Ni8zNjcxMzU0MjItYWYyMTczMjQtOGIzMS00NWQ3LTg5YzYtOGMwODUwMWYzNjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OGJjNDk1Y2Q3MmQzNTUwMzUwODU4YTllMWUzOWQ1OTAwZTdiN2I0ZmI4MTU5M2M5NzgxY2NkODU3YWZiYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HIE4BOCL4eQEHjY2CJU25nRSwDkLwj7C0ugrlWPQ16g)

上传一下完整nohup.out文件我看看？

**Comment by KkemChen** [comment]
[nohup.zip](https://github.com/user-attachments/files/16987975/nohup.zip)

**Comment by zhaocc1106** [comment]
<img width="921" alt="image" src="https://github.com/user-attachments/assets/a72b9049-85ad-426c-8102-4ccdbd37b614">
这里显示没有权限创建线程。你们的宿主机系统类型是？看下有没有容器有没有被限制创建线程？
ulimit -a
<img width="533" alt="image" src="https://github.com/user-attachments/assets/e87007a5-16fe-415f-b7bb-8bb603a9e7b9">

**Comment by KkemChen** [comment]
![image](https://github.com/user-attachments/assets/2a7ed848-162a-4337-8807-b76a67129cf7)
![image](https://github.com/user-attachments/assets/5139482d-b2e7-41c8-b4aa-4f877a3a2b9c)

**Comment by zhaocc1106** [comment]
<img width="971" alt="image" src="https://github.com/user-attachments/assets/6fcebad0-9611-4733-827a-d6c498613b13">
<img width="953" alt="image" src="https://github.com/user-attachments/assets/c61dc3e4-19ee-4aed-922f-2817d076bc9b">

参考这个试一下打开权限？
另外方便cat /etc/issue看下宿主机的系统版本吗？

**Comment by KkemChen** [comment]
Ubuntu 18.04.4 LTS

**Comment by KkemChen** [comment]
开了 privileged后 能跑了 
![image](https://github.com/user-attachments/assets/e2c7061c-4ce8-4751-b00f-5026b46c7814)

**Comment by zhaocc1106** [comment]
> 开了 privileged后 能跑了 ![image](https://private-user-images.githubusercontent.com/44298896/367138583-e2c7061c-4ce8-4751-b00f-5026b46c7814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg1MjYsIm5iZiI6MTcyNjE5ODIyNiwicGF0aCI6Ii80NDI5ODg5Ni8zNjcxMzg1ODMtZTJjNzA2MWMtNGNlOC00NzUxLWIwMGYtNTAyNmI0NmM3ODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YjgyZjkwMDYxYmY5NmQ4MjI2NzU4ZDc5NmRhZmViY2IyZGQ5NTE0YjNkODU1OTVjYmE0ZmEzYWU5OWNjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M0WCLnUCNNBx5rN8YyKUUX_1xXg3sjQCBdRPS-1gNyQ)

好的！看来还是权限不足
